"""
Makes a snippet for Roblox Studio's Command Bar that creates (or updates) scripts from
sync/ in the place, for files Azul can't map: Azul only syncs scripts that already exist
in Studio, so a file that arrives by `git pull` (made in a cloud session) logs "No
mapping found" and never reaches Studio, and whatever requires it waits forever.

  python3 tools/studio_upsert.py --since <git ref>      (every sync/ file added since)
  python3 tools/studio_upsert.py sync/Path/To/File.luau ...

writes tools/AddNewScripts.luau. In Studio (Edit mode, not playing): View > Command Bar,
paste the whole file, Enter. Each script is created where its path says, as the class
its name says (.server = Script, .client = LocalScript, else ModuleScript), or updated
if it's there; Azul then maps it (and writes the same text back to disk).
"""

import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "tools", "AddNewScripts.luau")
BRACKET = "=" * 6


def added_since(ref):
    names = subprocess.run(["git", "diff", "--diff-filter=A", "--name-only", ref, "HEAD", "--", "sync"],
                           cwd=ROOT, capture_output=True, text=True, check=True).stdout.split()
    return [n for n in names if n.endswith(".luau")]


def entry(path):
    parts = path.replace("\\", "/").split("/")
    assert parts[0] == "sync", f"{path} isn't under sync/"
    file = parts[-1]
    if file.endswith(".server.luau"):
        name, cls = file[:-len(".server.luau")], "Script"
    elif file.endswith(".client.luau"):
        name, cls = file[:-len(".client.luau")], "LocalScript"
    else:
        name, cls = file[:-len(".luau")], "ModuleScript"
    with open(os.path.join(ROOT, path), encoding="utf-8") as handle:
        source = handle.read()
    assert f"]{BRACKET}]" not in source, f"{path} holds the long-string closer"
    where = ", ".join(f'"{p}"' for p in parts[1:-1])
    return f'upsert({{ {where} }}, "{name}", "{cls}", [{BRACKET}[\n{source}]{BRACKET}])\n'


def main():
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        return
    files = added_since(args[1]) if args[0] == "--since" else args
    lines = [
        "-- Generated by tools/studio_upsert.py. Paste all of it into Studio's Command Bar (Edit",
        "-- mode, not while playing) and press Enter: it creates or updates these scripts.",
        'local ChangeHistoryService = game:GetService("ChangeHistoryService")',
        'local ScriptEditorService = game:GetService("ScriptEditorService")',
        "local function upsert(path, name, class, source)",
        "\tlocal parent = game:GetService(path[1])",
        "\tfor index = 2, #path do",
        "\t\tlocal child = parent:FindFirstChild(path[index])",
        "\t\tif not child then",
        '\t\t\tchild = Instance.new("Folder")',
        "\t\t\tchild.Name = path[index]",
        "\t\t\tchild.Parent = parent",
        "\t\tend",
        "\t\tparent = child",
        "\tend",
        "\tlocal script = parent:FindFirstChild(name)",
        "\tif script and script.ClassName ~= class then",
        '\t\twarn(`{script:GetFullName()} is a {script.ClassName}, not a {class}: left alone`)',
        "\t\treturn",
        "\tend",
        "\tlocal created = script == nil",
        "\tif not script then",
        "\t\tscript = Instance.new(class)",
        "\t\tscript.Name = name",
        "\t\tscript.Parent = parent",
        "\tend",
        "\tlocal ok = pcall(function()",
        "\t\tScriptEditorService:UpdateSourceAsync(script, function()",
        "\t\t\treturn source",
        "\t\tend)",
        "\tend)",
        "\tif not ok then",
        "\t\tscript.Source = source",
        "\tend",
        '\tprint(`{if created then "created" else "updated"} {script:GetFullName()}`)',
        "end",
        'ChangeHistoryService:SetWaypoint("Before AddNewScripts")',
    ]
    body = "".join(entry(f) for f in files)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n" + body + 'ChangeHistoryService:SetWaypoint("AddNewScripts")\n')
    print(f"{OUT}: {len(files)} script(s): " + ", ".join(os.path.basename(f) for f in files))


if __name__ == "__main__":
    main()
